runtime: python310

instance_class: F4
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

entrypoint: gunicorn -b :$PORT --workers 2 --threads 4 --timeout 300 app:app

env_variables:
  PYTHONUNBUFFERED: "1"
